// <auto-generated />
using System;
using Ambulanzsystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambulanzsystem.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AmbulanzprotokollExport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FormStateSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_state_snapshot");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Watermark")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("watermark");

                    b.HasKey("Id")
                        .HasName("pk_ambulanzprotokoll_exports");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_ambulanzprotokoll_exports_patient_id");

                    b.ToTable("ambulanzprotokoll_exports", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AmbulanzprotokollPage1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldTimestampsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("field_timestamps");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("FormStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_state");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ambulanzprotokoll_page1s");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_ambulanzprotokoll_page1s_patient_id");

                    b.ToTable("ambulanzprotokoll_page1s", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AmbulanzprotokollRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActorId").HasColumnType("integer").HasColumnName("actor_id");
                    b.Property<string>("ActorRole").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("actor_role");
                    b.Property<string>("CorrectionReason").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("correction_reason");
                    b.Property<DateTime>("FinalizedAt").HasColumnType("timestamp with time zone").HasColumnName("finalized_at");
                    b.Property<string>("FormStateSnapshotJson").IsRequired().HasColumnType("jsonb").HasColumnName("form_state_snapshot");
                    b.Property<int>("PatientId").HasColumnType("integer").HasColumnName("patient_id");
                    b.Property<int>("Version").HasColumnType("integer").HasColumnName("version");
                    b.HasKey("Id").HasName("pk_ambulanzprotokoll_revisions");
                    b.HasIndex("PatientId", "Version").IsUnique().HasDatabaseName("ix_ambulanzprotokoll_revisions_patient_id_version");
                    b.ToTable("ambulanzprotokoll_revisions", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_audit_logs_patient_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AmbulanzprotokollRevision", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ambulanzprotokoll_revisions_patients_patient_id");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Body", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPartsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body_parts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bodies");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_bodies_patient_id");

                    b.ToTable("bodies", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.OperationScene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccessWindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_window_end");

                    b.Property<DateTime?>("AccessWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_window_start");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("integer")
                        .HasColumnName("organisation_id");

                    b.Property<int?>("ParentSceneId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_scene_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operation_scenes");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_operation_scenes_organisation_id");

                    b.HasIndex("ParentSceneId")
                        .HasDatabaseName("ix_operation_scenes_parent_scene_id");

                    b.ToTable("operation_scenes", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Atmung")
                        .HasColumnType("boolean")
                        .HasColumnName("atmung");

                    b.Property<bool?>("Blutung")
                        .HasColumnType("boolean")
                        .HasColumnName("blutung");

                    b.Property<Guid?>("ClientGeneratedId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_generated_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("Dringend")
                        .HasColumnType("boolean")
                        .HasColumnName("dringend");

                    b.Property<string>("FieldTimestampsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("field_timestamps");

                    b.Property<string>("HumanReadableId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("human_readable_id");

                    b.Property<string>("IndoorLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("indoor_location");

                    b.Property<bool?>("Kontaminiert")
                        .HasColumnType("boolean")
                        .HasColumnName("kontaminiert");

                    b.Property<double?>("LatitudePatient")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude_patient");

                    b.Property<double?>("LocationAccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("location_accuracy_meters");

                    b.Property<string>("LocationSource")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_source");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("location_updated_at");

                    b.Property<double?>("LongitudePatient")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude_patient");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OperationSceneId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_scene_id");

                    b.Property<bool?>("Radialispuls")
                        .HasColumnType("boolean")
                        .HasColumnName("radialispuls");

                    b.Property<bool?>("Transport")
                        .HasColumnType("boolean")
                        .HasColumnName("transport");

                    b.Property<string>("Triagefarbe")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("triagefarbe");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("integer")
                        .HasColumnName("user_id_user");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("ClientGeneratedId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_client_generated_id")
                        .HasFilter("client_generated_id IS NOT NULL");

                    b.HasIndex("OperationSceneId")
                        .HasDatabaseName("ix_patients_operation_scene_id");

                    b.HasIndex("UserIdUser")
                        .HasDatabaseName("ix_patients_user_id_user");

                    b.ToTable("patients", null, t =>
                        {
                            t.HasCheckConstraint("ck_patients_triagefarbe", "triagefarbe IN ('rot','gelb','gruen','schwarz')");
                        });
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.QrCodeLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventSceneId")
                        .HasColumnType("integer")
                        .HasColumnName("event_scene_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<double>("ExpiresInHours")
                        .HasColumnType("double precision")
                        .HasColumnName("expires_in_hours");

                    b.Property<DateTime?>("FirstLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_login");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("qr_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_qr_code_logins");

                    b.HasIndex("EventSceneId")
                        .HasDatabaseName("ix_qr_code_logins_event_scene_id");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasDatabaseName("ix_qr_code_logins_qr_token");

                    b.ToTable("qr_code_logins", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.QrCodePatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("OperationSceneId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_scene_id");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("qr_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_qr_code_patients");

                    b.HasIndex("OperationSceneId")
                        .HasDatabaseName("ix_qr_code_patients_operation_scene_id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_qr_code_patients_patient_id")
                        .HasFilter("patient_id IS NOT NULL");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasDatabaseName("ix_qr_code_patients_qr_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_qr_code_patients_user_id");

                    b.ToTable("qr_code_patients", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assigned_location");

                    b.Property<int?>("AssignedPatientId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_patient_id");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OperationSceneId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_scene_id");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("AssignedPatientId")
                        .HasDatabaseName("ix_teams_assigned_patient_id");

                    b.HasIndex("OperationSceneId")
                        .HasDatabaseName("ix_teams_operation_scene_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EventSceneId")
                        .HasColumnType("integer")
                        .HasColumnName("event_scene_id");

                    b.Property<DateTime?>("FirstLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_login_time");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_time");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("RequiresPasswordChange")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_password_change");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EventSceneId")
                        .HasDatabaseName("ix_users_event_scene_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OperationalMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_operational_metadata");

                    b.ToTable("operational_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_operational_metadata_deployment_id", "\"key\" = 'deployment_id'");
                        });
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AmbulanzprotokollExport", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ambulanzprotokoll_exports_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.AmbulanzprotokollPage1", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.Patient", "Patient")
                        .WithOne("AmbulanzprotokollPage1")
                        .HasForeignKey("Ambulanzsystem.Api.Domain.AmbulanzprotokollPage1", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ambulanzprotokoll_page1s_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Body", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.Patient", "Patient")
                        .WithOne("Body")
                        .HasForeignKey("Ambulanzsystem.Api.Domain.Body", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bodies_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.OperationScene", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_operation_scenes_organisations_organisation_id");

                    b.HasOne("Ambulanzsystem.Api.Domain.OperationScene", "ParentScene")
                        .WithMany("SubSites")
                        .HasForeignKey("ParentSceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_operation_scenes_operation_scenes_parent_scene_id");

                    b.Navigation("Organisation");

                    b.Navigation("ParentScene");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Patient", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.OperationScene", "OperationScene")
                        .WithMany("Patients")
                        .HasForeignKey("OperationSceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patients_operation_scenes_operation_scene_id");

                    b.HasOne("Ambulanzsystem.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_patients_users_user_id_user");

                    b.Navigation("OperationScene");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.QrCodeLogin", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.OperationScene", "EventScene")
                        .WithMany()
                        .HasForeignKey("EventSceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_qr_code_logins_operation_scenes_event_scene_id");

                    b.Navigation("EventScene");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.QrCodePatient", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.OperationScene", "OperationScene")
                        .WithMany()
                        .HasForeignKey("OperationSceneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_qr_code_patients_operation_scenes_operation_scene_id");

                    b.HasOne("Ambulanzsystem.Api.Domain.Patient", "Patient")
                        .WithOne("QrCodePatient")
                        .HasForeignKey("Ambulanzsystem.Api.Domain.QrCodePatient", "PatientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_qr_code_patients_patients_patient_id");

                    b.HasOne("Ambulanzsystem.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_qr_code_patients_users_user_id");

                    b.Navigation("OperationScene");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Team", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.Patient", "AssignedPatient")
                        .WithMany()
                        .HasForeignKey("AssignedPatientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_teams_patients_assigned_patient_id");

                    b.HasOne("Ambulanzsystem.Api.Domain.OperationScene", "OperationScene")
                        .WithMany("Teams")
                        .HasForeignKey("OperationSceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_operation_scenes_operation_scene_id");

                    b.Navigation("AssignedPatient");

                    b.Navigation("OperationScene");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.User", b =>
                {
                    b.HasOne("Ambulanzsystem.Api.Domain.OperationScene", "EventScene")
                        .WithMany()
                        .HasForeignKey("EventSceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_operation_scenes_event_scene_id");

                    b.Navigation("EventScene");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.OperationScene", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("SubSites");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.Patient", b =>
                {
                    b.Navigation("AmbulanzprotokollPage1");

                    b.Navigation("Body");

                    b.Navigation("QrCodePatient");
                });

            modelBuilder.Entity("Ambulanzsystem.Api.Domain.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
