/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/qr-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Responder QR login (online-only). Short-lived token, no refresh token.
         * @description Exchanges an active responder login QR token for a short-lived event-scoped access token.
         */
        post: operations["qrLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Responder username/password login (token type=user).
         * @description Authenticates a responder username and password and returns an access and refresh token pair.
         */
        post: operations["userLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin or Leitstelle login. Token type reflects the user's role.
         * @description Authenticates an Admin or Leitstelle account and returns its role-specific token pair.
         */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token (old is revoked, new pair issued).
         * @description Consumes one valid refresh token and rotates it into a new access and refresh token pair.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the given refresh token. Policy AuthenticatedUser.
         * @description Revokes the submitted refresh token for the authenticated session.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route-guard check. Policy TriageWrite (any authenticated session).
         * @description Confirms that the current bearer token is valid and returns its effective role.
         */
        post: operations["validateToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * DEV ONLY. Password-free login for seeded accounts. 404 unless Development env AND Features__EnableDevLogin.
         * @description Creates a non-refreshable seeded-account token when the explicit development-login feature is enabled.
         */
        post: operations["developmentLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users for the Admin revocation view. Policy AdminOnly.
         * @description Returns the users visible in the Admin account-revocation view.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user (admin, leitstelle, or responder). Policy AdminOnly. New admin/leitstelle users get requiresPasswordChange=true.
         * @description Creates an Admin, Leitstelle, or responder account with the requested scope.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change own password. Verifies current password, regenerates security stamp (invalidates all live tokens), revokes all refresh tokens. Policy AuthenticatedUser.
         * @description Changes the caller's password and invalidates its existing access and refresh tokens.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End a user's access early. Policy LeitstelleOrAdmin. Blocks new actions/reads; no forced client logout.
         * @description Ends access for the authorized target account identified by the path ID.
         */
        post: operations["revokeUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/self-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A responder/session ends its own access by choice. Policy TriageWrite.
         * @description Ends the authenticated responder or QR session's own access.
         */
        post: operations["cancelOwnAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login-qr-codes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-generate responder login QR codes for an event. Policy LeitstelleOrAdmin.
         * @description Generates the requested number of responder login QR codes for an authorized top-level event.
         */
        post: operations["generateLoginQrCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login-qr-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List login QR codes. Policy LeitstelleOrAdmin.
         * @description Lists responder login QR codes within the caller's authorized event scope and optional filters.
         */
        get: operations["listLoginQrCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login-qr-codes/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a login QR code early. Policy LeitstelleOrAdmin.
         * @description Revokes one responder login QR code within the caller's authorized event scope.
         */
        post: operations["revokeLoginQrCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patient-qr-codes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-generate unbound patient QR codes (64-char random tokens). Policy AdminOnly.
         * @description Generates unbound random patient QR tokens for later printing and assignment.
         */
        post: operations["generatePatientQrCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patient-qr-codes/unused": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List codes not yet bound to a patient (for printing). Policy LeitstelleOrAdmin.
         * @description Returns patient QR tokens that are not currently bound to a patient.
         */
        get: operations["listUnusedPatientQrCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operation-scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scenes visible to the session (admin/leitstelle = all current, responder/qr = authorized event subtree within access window). Policy TriageWrite.
         * @description Lists the operation scenes visible to the current session and its event scope.
         */
        get: operations["listOperationScenes"];
        put?: never;
        /**
         * Create or update a scene (upsert by optional id). Policy LeitstelleOrAdmin. parentSceneId marks a sub-site; max one nesting level, cycles rejected.
         * @description Creates a scene or updates the existing scene identified in the request within the caller's authorized scope.
         */
        post: operations["saveOperationScene"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operation-scenes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an EMPTY scene. Policy AdminOnly. Deactivate scenes with linked records instead.
         * @description Deletes an empty operation scene; linked patients, sub-sites, and assigned user accounts (including revoked accounts) block deletion so account scope is preserved.
         */
        delete: operations["deleteOperationScene"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organisations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organisations. Policy AdminOnly.
         * @description Lists organisations available for operation-scene administration.
         */
        get: operations["listOrganisations"];
        put?: never;
        /**
         * Create an organisation. Policy AdminOnly.
         * @description Creates an organisation for later assignment to operation scenes.
         */
        post: operations["createOrganisation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List teams for a scene. Policy TriageWrite.
         * @description Lists the coordination teams assigned to the requested operation scene.
         */
        get: operations["listTeams"];
        put?: never;
        /**
         * Create a team in a scene. Policy LeitstelleOrAdmin.
         * @description Creates a coordination team in an authorized operation scene.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update any subset of optional coordination fields (FR-TEAM-07 — every field independently optional/clearable). Policy TriageWrite.
         * @description Updates the supplied coordination fields for the identified team. Team coordination is online-only in V1: requests carry no client timestamp, disjoint fields are updated independently, and concurrent writes to the same field use database-arrival order.
         */
        put: operations["updateTeam"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List patients linked to a scene (situation room + patient overview). Policy TriageWrite. Every request is read-audit-logged (D7).
         * @description Lists patients linked to the requested visible operation scene and records the read in the audit log.
         */
        get: operations["listPersons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verify-patient-qr-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan a patient QR tag. Unknown token -> 404. Unbound -> creates Patient + fully-seeded Body, binds code, links scene (201). Bound -> returns existing patient, refreshes scene link (200). Concurrency-safe (row lock) — parallel scans of the same code yield the same patient. Online-only. Policy TriageWrite.
         * @description Resolves a patient QR token, creating and binding a patient when the token is still unbound.
         */
        post: operations["verifyPatientQrCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a patient without a QR code. Idempotent on clientGeneratedId (D3): replaying the same UUID returns the already-created patient (200) instead of a duplicate (201 on first create). Server generates humanReadableId (no patient-identifying content). Policy TriageWrite.
         * @description Creates an untagged patient idempotently from the caller-provided client generation ID.
         */
        post: operations["createManualPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{id}/update-triage-color": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record-only START triage write (D1). triageColor validated against rot|gelb|gruen|schwarz (shared normalize helper maps 'grün'->'gruen', trims, lowercases; everything else incl. 'blau' -> 400). Field-level LWW merge using clientUpdatedAt when supplied (NFR-SAFE-08/09). Audit-logged with before/after. Publishes realtime update. Policy TriageWrite.
         * @description Updates supplied START triage fields and emits the resulting audit and realtime records.
         */
        post: operations["updatePatientTriage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{id}/respiration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set the breathing-sufficient flag. Publishes realtime update. Policy TriageWrite.
         * @description Updates the patient's breathing-sufficient flag and publishes the resulting patient state.
         */
        post: operations["updatePatientRespiration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update patient position (auto-captured device GPS or manual correction, FR-LOC-05/06). Publishes realtime update. Policy TriageWrite.
         * @description Updates the patient's validated GPS or manually corrected location and publishes the new state.
         */
        post: operations["updatePatientLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{id}/reassign-qr-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unbind the patient's current QR code and bind the given UNBOUND code (mis-attached tag correction, FR-QR-07). Policy TriageWrite.
         * @description Replaces the patient's current QR binding with the supplied unbound patient QR token.
         */
        post: operations["reassignPatientQrCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{id}/triage-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Triage change history for a patient, sourced from the audit log (FR-SIT-08). Policy LeitstelleOrAdmin.
         * @description Returns the patient's triage changes in chronological order from the audit log.
         */
        get: operations["getPatientTriageHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{patientId}/ambulanzprotokoll-page1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the page-1 record, or a default-shaped empty draft if none saved yet. Read-audit-logged. Policy TriageWrite.
         * @description Returns the saved page-one protocol or a default-shaped draft for the requested patient.
         */
        get: operations["getAmbulanzprotokollPage1"];
        /**
         * Upsert the page-1 record. Draft accepts any partial data; missing branches are merged with the default state; concurrent saves merge field-level LWW (older non-empty values survive empty newer fields, NFR-SAFE-09). status=finalized stamps finalizedAt and returns soft-validation warnings — never a hard block for empty fields. Post-finalize saves stay allowed (Leitstelle/Admin any form; responder their own records); all audit-logged. Policy TriageWrite.
         * @description Merges and saves page-one protocol data and returns the persisted record with any server validation warnings.
         */
        put: operations["saveAmbulanzprotokollPage1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{patientId}/ambulanzprotokoll-page1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JSON export (V1 export format, FR-DOC-09). Wraps formState with patient/event metadata, generation timestamp, and an actor watermark (NFR-SEC-10). The export is persisted server-side (long-term archive, FR-DOC-14) and the action is audit-logged. Admin and Leitstelle may export authorized patients; a named responder may export only a patient they own. Anonymous QR sessions and cross-owner responders receive 403, with no archive or success audit created.
         * @description Generates, archives, and audit-logs the authorized JSON export for the requested patient's protocol.
         */
        get: operations["exportAmbulanzprotokollPage1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/body-parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full region-toggle body state for a patient (all canonical keys always present). Policy TriageWrite.
         * @description Returns the complete canonical body-region marker state for the requested patient.
         */
        get: operations["getBodyParts"];
        /**
         * Toggle one region's marker. bodyPartId validated against the canonical key list. Publishes realtime update. Policy TriageWrite.
         * @description Sets one validated body-region marker and returns the patient's complete updated marker state.
         */
        put: operations["updateBodyPart"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query the append-only audit log (D7). Policy AdminOnly.
         * @description Queries append-only audit entries using the supplied patient, action, entity type, time, and paging filters.
         */
        get: operations["queryAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * In-process operational counters (reset on restart). Policy AdminOnly.
         * @description Returns process-local request, authentication, database, and realtime counters for operators.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health endpoint (NFR-OPS-01). Unauthenticated. A realtime publish queue backlog is degraded.
         * @description Reports unauthenticated database and realtime readiness. Database or realtime dispatcher unavailable is unhealthy (HTTP 503).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @constant */
            status: "error";
            message: string;
        };
        /** @enum {string} */
        Role: "admin" | "leitstelle" | "responder";
        /**
         * @description Canonical output uses ASCII `gruen` (D5); input `grün` is accepted as an alias and normalized to `gruen`. `blau` is invalid in V1.
         * @enum {string}
         */
        TriageColor: "rot" | "gelb" | "gruen" | "schwarz";
        /**
         * @description Accepts Unicode `grün` as an input alias; responses always serialize the canonical ASCII value `gruen`.
         * @enum {string}
         */
        TriageColorInput: "rot" | "gelb" | "gruen" | "grün" | "schwarz";
        CredentialsRequest: {
            username: string;
            password: string;
        };
        User: {
            id: number;
            username: string;
            role: components["schemas"]["Role"];
            /** @enum {string} */
            accountType: "permanent" | "event";
            eventSceneId?: number | null;
            requiresPasswordChange?: boolean;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LoginQrCode: {
            id: number;
            qrToken: string;
            eventSceneId: number;
            /** Format: date-time */
            firstLogin?: string | null;
            /**
             * Format: date-time
             * @description Null until first login; then firstLogin + configured window.
             */
            expiresAt?: string | null;
            expiresInHours?: number;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        OperationScene: {
            id: number;
            name: string;
            description?: string | null;
            organisationId?: number | null;
            /** @description Null = top-level scene = the event (D6). */
            parentSceneId?: number | null;
            /** Format: date-time */
            accessWindowStart?: string | null;
            /** Format: date-time */
            accessWindowEnd?: string | null;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Organisation: {
            id: number;
            name: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Team: {
            id: number;
            operationSceneId: number;
            name: string;
            /** @enum {string|null} */
            status?: "free" | "busy" | "unavailable" | null;
            assignedPatientId?: number | null;
            assignedLocation?: string | null;
            contactInfo?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Patient: {
            id: number;
            /** @description Set for manually created patients; no patient-identifying content (FR-PAT-07). */
            humanReadableId?: string | null;
            /** Format: uuid */
            clientGeneratedId?: string | null;
            name?: string | null;
            triagefarbe?: components["schemas"]["TriageColor"] | null;
            atmung?: boolean | null;
            blutung?: boolean | null;
            radialispuls?: boolean | null;
            transport?: boolean | null;
            dringend?: boolean | null;
            kontaminiert?: boolean | null;
            longitudePatient?: number | null;
            latitudePatient?: number | null;
            /** @enum {string|null} */
            locationSource?: "gps" | "manual" | null;
            locationAccuracyMeters?: number | null;
            indoorLocation?: string | null;
            /** Format: date-time */
            locationUpdatedAt?: string | null;
            operationSceneId: number;
            /** @description Whether a patient QR tag is currently bound. */
            qrCodeBound?: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VerifyQrResult: {
            patient: components["schemas"]["Patient"];
            /** @description True when this scan created the patient. */
            created: boolean;
        };
        TriageHistoryEntry: {
            /** Format: date-time */
            timestamp: string;
            actorId: number;
            /** @enum {string} */
            actorRole?: "admin" | "leitstelle" | "user" | "qr";
            /** @description e.g. triagefarbe */
            field: string;
            before: string | null;
            after: string | null;
        };
        BodyParts: {
            idpatient: number;
            /** @description One entry per key in contract/body-regions.json; 0 = unmarked, non-zero = marked. */
            bodyParts: {
                [key: string]: number;
            };
            /** Format: date-time */
            updatedAt?: string;
        };
        ProtokollRecord: {
            patientId: number;
            /** @enum {string} */
            status: "draft" | "finalized";
            formState: components["schemas"]["ProtokollFormState"];
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            finalizedAt?: string | null;
        };
        /** @description Canonical page-1 state; every branch references the Draft 2020-12 source schema. */
        ProtokollFormState: {
            incident?: components["schemas"]["incident"];
            patient?: components["schemas"]["patient"];
            assessment_primary?: components["schemas"]["assessment_primary"];
            assessment_secondary?: components["schemas"]["assessment_secondary"];
            medications_administered?: components["schemas"]["medications_administered"];
            vitals?: components["schemas"]["vitals"];
            measures?: components["schemas"]["measures"];
            history?: components["schemas"]["history"];
            disposition?: components["schemas"]["disposition"];
            signatures?: components["schemas"]["signatures"];
        };
        ProtokollExport: {
            metadata: {
                patientId: number;
                humanReadableId?: string | null;
                operationSceneId: number;
                operationSceneName?: string;
                eventSceneId?: number;
                /** Format: date-time */
                generatedAt: string;
                /** @description Identifies the exporting actor (NFR-SEC-10). */
                watermark: string;
                schemaVersion?: string;
            };
            protokoll: components["schemas"]["ProtokollRecord"];
        };
        AuditEntry: {
            id: number;
            /** Format: date-time */
            timestamp: string;
            /** @description Null for audit events without an authenticated database user. */
            actorId: number | null;
            /** @enum {string} */
            actorRole: "admin" | "leitstelle" | "user" | "qr";
            /** @enum {string} */
            action: "read" | "write" | "export" | "login" | "revoke";
            entityType: string;
            entityId?: number | null;
            patientId?: number | null;
            changedFields?: string[] | null;
            /** @description JSON-encoded value before the action */
            before?: string | null;
            /** @description JSON-encoded value after the action */
            after?: string | null;
        };
        incident: {
            ambulanzort?: string;
            /** @description ISO date (visual: T T M M J J) */
            datum?: string | null;
            uhrzeit_beginn?: string | null;
            dnr_san_1?: string;
            dnr_san_2?: string;
            dnr_san_3?: string;
            dnr_na?: string;
            pls_nummer?: string;
            funkrufname?: string;
        };
        patient: {
            familienname?: string;
            vorname?: string;
            /** @enum {string|null} */
            geschlecht?: "d" | "m" | "w" | null;
            vers_nr?: string;
            geburtsdatum?: string | null;
            adresse?: string;
            staat?: string;
            telefon?: string;
            arbeitgeber?: string;
            versicherungstraeger?: string;
            familienstand?: string;
        };
        assessment_primary: {
            /** @description Array for checkbox-group uniformity; at most one NACA score. */
            naca?: ("I" | "II" | "III" | "IV" | "V" | "VI" | "VII")[];
            atemweg?: ("frei" | "gefaehrdet" | "verlegt")[];
            atmung?: ("Apnoe" | "Schnappatmung" | "Zyanose" | "unauffaellig" | "Dyspnoe" | "Atemgeraeusche" | "andere Atemstoerungen")[];
            kreislauf?: ("Puls peripher tastbar" | "Tachykardie" | "Bradykardie" | "blass" | "kalt" | "unauffaellig" | "Starke Blutung" | "geroetet" | "schweissig" | "erwaermt")[];
            bewusstsein?: ("Wach" | "Getruebt" | "Bewusstlos" | "Agitiert")[];
            angen_notfallzeit?: {
                zeit?: string | null;
                gt24h?: boolean;
                unbekannt?: boolean;
            };
        };
        assessment_secondary: {
            anamnese_text?: string;
            /** @description Coordinate-based typed markers — independent of the triage region-toggle body map (OD-05). */
            bodymap?: {
                /** @enum {unknown} */
                view: "front" | "back";
                /** @enum {unknown} */
                marker: "wunde" | "fraktur" | "schmerz" | "prellung" | "amputation" | "verbrennung" | "luxation";
                /** @description Percent of silhouette width. */
                x: number;
                /** @description Percent of silhouette height. */
                y: number;
            }[];
        };
        medications_administered: {
            medikament?: string;
            dosis?: string;
            art?: string;
            uhrzeit?: string | null;
        }[];
        pupilChecks: ("eng" | "mittel" | "weit" | "entrundet" | "prompte Lichtreflexe" | "verlangsamte Lichtreflexe" | "lichtstarr")[];
        vitals: {
            pupillen?: {
                R?: components["schemas"]["pupilChecks"];
                L?: components["schemas"]["pupilChecks"];
            };
            schmerz?: number | null;
            schmerz_nicht_beurteilbar?: boolean;
            gcs_augenoeffnen?: number | null;
            gcs_verbale_reaktion?: number | null;
            gcs_motorische_reaktion?: number | null;
            /** @description Auto-computed eyes+verbal+motor when all three present. */
            gcs_summe?: number | null;
            keine?: boolean;
            rr?: string;
            puls?: string;
            puls_rhythmus?: ("rhy." | "arrhy.")[];
            af?: string;
            temp?: string;
            bz?: string;
            etco2?: string;
            spo2?: string;
            o2_l_min?: string;
            o2_beatmung_l_min?: string;
        };
        measures: {
            herz_kreislauf?: {
                massnahmen?: ("peripherven. Zugang / IO Zugang" | "Herzdruckmassage" | "Defibrillation/Kardiov." | "Schrittmacher extern")[];
                dnr?: string;
                anzahl?: string;
                letzte_joule?: string;
                freq?: string;
                mv?: string;
            };
            atmung?: {
                massnahmen?: ("Absaugen" | "oral" | "nasal" | "endotracheal" | "Intubation" | "Wendltubus" | "Guedeltubus" | "Larynxtubus" | "endotracheal (oral)" | "endotracheal (nasal)" | "Beatmung" | "assistiert" | "kontrolliert" | "manuell" | "maschinell")[];
                dnr?: string;
                af?: string;
                amv?: string;
                peep?: string;
            };
            weitere_massnahmen?: {
                massnahmen?: ("Verband" | "Blutstillung" | "Abbinden" | "Lagerung" | "12-Abl.-EKG" | "Monitoring" | "HF" | "RR" | "SpO2" | "4-Abl.-EKG" | "etCO2" | "Schienung" | "HWS" | "Spineboard" | "Vakuummatratze" | "Extremitaet")[];
                abbinden_zeit?: string | null;
                lagerung_art?: string;
            };
        };
        history: {
            allergien?: string;
            medikamente?: string;
            patientengeschichte_vorerkrankungen?: string;
            letzte_orale_aufnahme?: string;
            ereignisse_zuvor?: string;
            risikofaktoren?: string;
        };
        disposition: {
            abschlussart?: ("Uebergabe:" | "Revers (Ruecks.)" | "Belassung" | "Entf. selbstst. o. Revers")[];
            klinischer_zustand?: ("verbessert" | "gleich" | "verschlechtert")[];
            uhrzeit_ende?: string | null;
            org?: string;
            typ?: string;
            kennung?: string;
            angehoerige_in_kenntnis?: ("durch RD" | "durch Polizei" | "durch Pat/andere")[];
            kontaktdaten?: string;
        };
        signatures: {
            /** @description PNG data URL from the signature pad. Present because the paper form has it; never required (FR-DOC-13). */
            entlass_san_na?: string | null;
        };
    };
    responses: {
        /** @description Missing, invalid, expired, or live-revoked credentials. Revocation returns 401 immediately and blocks new actions and reads (FR-AUTH-09). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted, including role denial and an existing resource outside the session's event scene boundary (NFR-SEC-02). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Entity not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation failure. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Login or refresh-token rate limit exceeded (fixed window 10/60s per IP, NFR-SEC-05). */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        idPath: number;
        patientIdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    qrLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    qr_code: string;
                };
            };
        };
        responses: {
            /** @description Logged in. Token has type=qr, scoped to the event scene subtree. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        token: string;
                        /** @description Top-level scene this QR grants access to. */
                        eventSceneId?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    userLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Logged in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        token: string;
                        refreshToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Logged in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        token: string;
                        refreshToken: string;
                        requiresPasswordChange: boolean;
                        role: components["schemas"]["Role"];
                        /** @description Assigned top-level event for an event-scoped account; null for a permanent account. */
                        eventSceneId?: number | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description New token pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        refreshToken: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    validateToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        isValid: true;
                        /** @enum {string} */
                        role?: "admin" | "leitstelle" | "user" | "qr";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    developmentLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "admin" | "user";
                };
            };
        };
        responses: {
            /** @description Logged in with a development-bypass token. It is intentionally non-refreshable and requiresPasswordChange is always false. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        token: string;
                        /** @description Username of the real seeded account represented by the token. */
                        username: string;
                        /** @constant */
                        requiresPasswordChange: false;
                        /** @description Optional for compatibility; omitted for development-bypass sessions. */
                        refreshToken?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Not available (any non-dev configuration). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    role: components["schemas"]["Role"];
                    /**
                     * @default permanent
                     * @enum {string}
                     */
                    accountType?: "permanent" | "event";
                    /** @description Required when accountType=event; access is scoped to this top-level scene's subtree and its access window. */
                    eventSceneId?: number;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Username already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Changed. All outstanding sessions for this user are now invalid. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelOwnAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    generateLoginQrCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    number: number;
                    /** @description Top-level scene (event) the codes grant access to. */
                    eventSceneId: number;
                    /**
                     * @description Access window from first login (FR-AUTH-08).
                     * @default 12
                     */
                    expiresInHours?: number;
                };
            };
        };
        responses: {
            /** @description Generated codes. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginQrCode"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listLoginQrCodes: {
        parameters: {
            query?: {
                eventSceneId?: number;
                unusedOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Codes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginQrCode"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeLoginQrCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    generatePatientQrCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    number: number;
                };
            };
        };
        responses: {
            /** @description Generated codes. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listUnusedPatientQrCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unbound codes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listOperationScenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationScene"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveOperationScene: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Present = update */
                    id?: number;
                    name: string;
                    description?: string;
                    organisationId?: number;
                    /** @description Parent = the event (D6). Null = this scene IS the event. */
                    parentSceneId?: number;
                    /** Format: date-time */
                    accessWindowStart?: string;
                    /** Format: date-time */
                    accessWindowEnd?: string;
                    /** @default true */
                    active?: boolean;
                };
            };
        };
        responses: {
            /** @description Saved scene. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationScene"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteOperationScene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Linked patients, sub-sites, or assigned user accounts (including revoked accounts); deletion blocked. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOrganisations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organisations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrganisation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organisation"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTeams: {
        parameters: {
            query: {
                operationSceneId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Teams. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    operationSceneId: number;
                    /** @description Name or radio call sign. */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string|null} */
                    status?: "free" | "busy" | "unavailable" | null;
                    assignedPatientId?: number | null;
                    assignedLocation?: string | null;
                    contactInfo?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPersons: {
        parameters: {
            query: {
                operationSceneId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyPatientQrCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    qr_code: string;
                    operationSceneId: number;
                };
            };
        };
        responses: {
            /** @description Existing patient returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyQrResult"];
                };
            };
            /** @description New patient created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyQrResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Unknown QR token — rejected (UC-04). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createManualPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    operationSceneId: number;
                    name?: string;
                    /**
                     * Format: uuid
                     * @description Offline idempotency key generated by the client.
                     */
                    clientGeneratedId?: string;
                };
            };
        };
        responses: {
            /** @description Idempotent replay — patient already existed for this clientGeneratedId. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updatePatientTriage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    triageColor?: components["schemas"]["TriageColorInput"];
                    respiration?: boolean;
                    blutung?: boolean;
                    radialispuls?: boolean;
                    transport?: boolean;
                    dringend?: boolean;
                    kontaminiert?: boolean;
                    /**
                     * Format: date-time
                     * @description Client-side write timestamp for offline replay merge; must not be more than five minutes ahead of server UTC. Older timestamps remain valid.
                     */
                    clientUpdatedAt?: string;
                };
            };
        };
        responses: {
            /** @description Updated patient. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePatientRespiration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    respiration: boolean;
                    /**
                     * Format: date-time
                     * @description Must not be more than five minutes ahead of server UTC. Older timestamps remain valid.
                     */
                    clientUpdatedAt?: string;
                };
            };
        };
        responses: {
            /** @description Updated patient. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePatientLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description WGS84 latitude, inclusive range -90 through 90. */
                    lat: number;
                    /** @description WGS84 longitude, inclusive range -180 through 180. */
                    lng: number;
                    /**
                     * @description Only device GPS or explicit manual correction is accepted.
                     * @default gps
                     * @enum {string}
                     */
                    source?: "gps" | "manual";
                    /** @description Finite, non-negative reported GPS accuracy; UI flags >10m as unreliable (FR-LOC-07). */
                    accuracyMeters?: number;
                    /** @description Optional free text: tent/sector/room/floor/treatment bay (FR-LOC-08). */
                    indoorLocation?: string;
                    /**
                     * Format: date-time
                     * @description Client-side write timestamp for offline replay merge (NFR-SAFE-08/09); must not be more than five minutes ahead of server UTC. Older timestamps remain valid.
                     */
                    clientUpdatedAt?: string;
                };
            };
        };
        responses: {
            /** @description Updated patient. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reassignPatientQrCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    qr_code: string;
                };
            };
        };
        responses: {
            /** @description Updated patient with new QR binding. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Given code is already bound to another patient. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPatientTriageHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["idPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chronological triage changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageHistoryEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAmbulanzprotokollPage1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: components["parameters"]["patientIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Form record (formState conforms to schemas/ambulanzprotokoll-page1.schema.json). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtokollRecord"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Patient does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveAmbulanzprotokollPage1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: components["parameters"]["patientIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "draft" | "finalized";
                    formState: components["schemas"]["ProtokollFormState"];
                    /**
                     * Format: date-time
                     * @description Local edit timestamp for newer-wins comparison; must not be more than five minutes ahead of server UTC. Older timestamps remain valid.
                     */
                    clientUpdatedAt?: string;
                };
            };
        };
        responses: {
            /** @description Saved record (merged server state) plus any finalize warnings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtokollRecord"] & {
                        warnings: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Patient does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportAmbulanzprotokollPage1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: components["parameters"]["patientIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtokollExport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getBodyParts: {
        parameters: {
            query: {
                idpatient: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region-state map, one entry per key in contract/body-regions.json. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyParts"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBodyPart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    idpatient: number;
                    /** @description One key from contract/body-regions.json. */
                    bodyPartId: string;
                    isClicked: boolean;
                };
            };
        };
        responses: {
            /** @description Updated full body state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyParts"];
                };
            };
            /** @description Unknown bodyPartId. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    queryAuditLog: {
        parameters: {
            query?: {
                patientId?: number;
                action?: "read" | "write" | "export" | "login" | "revoke";
                /** @description Exact audited entity category, for example `patient` or `scene_snapshot`. */
                entityType?: string;
                from?: string;
                to?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        entries: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalRequests?: number;
                        authFailures?: number;
                        dbErrors?: number;
                        realtimeConnected?: boolean;
                        realtimePendingQueue?: number;
                        realtimeDroppedMessages?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy or degraded health report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "healthy" | "degraded";
                        /** @constant */
                        database?: "healthy";
                        /** @enum {string} */
                        realtime?: "healthy" | "degraded";
                    };
                };
            };
            /** @description Unhealthy. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "unhealthy";
                        /** @enum {string} */
                        database: "healthy" | "unhealthy";
                        /** @enum {string} */
                        realtime: "healthy" | "degraded" | "unhealthy";
                    };
                };
            };
        };
    };
}
